package org.hotswap.hotswaphelper.utils;

import com.google.common.base.Joiner;
import com.intellij.execution.configurations.ModuleRunProfile;
import com.intellij.execution.configurations.RunProfile;
import com.intellij.openapi.externalSystem.model.execution.ExternalSystemTaskExecutionSettings;
import com.intellij.openapi.externalSystem.service.execution.ExternalSystemRunConfiguration;
import com.intellij.openapi.project.Project;
import org.apache.commons.lang3.StringUtils;
import org.hotswap.hotswaphelper.settings.HotSwapHelperPluginSettingsProvider;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Set;

/**
 * Utility for Gradle project detection and HotSwap init script management.
 *
 * @author bruce ge
 */
public class GradleUtils {

    public static final String GRADLE_SYSTEM_ID = "GRADLE";
    public static final String INIT_SCRIPT_NAME = "hotswap-init.gradle";

    /**
     * Checks if the given RunProfile is a Gradle run configuration (running via Gradle).
     */
    public static boolean isGradleRunConfiguration(@Nullable RunProfile profile) {
        if (profile == null) {
            return false;
        }
        if (profile instanceof ExternalSystemRunConfiguration) {
            ExternalSystemRunConfiguration externalConfig = (ExternalSystemRunConfiguration) profile;
            ExternalSystemTaskExecutionSettings settings = externalConfig.getSettings();
            if (settings != null && settings.getExternalSystemId() != null) {
                return GRADLE_SYSTEM_ID.equalsIgnoreCase(settings.getExternalSystemId().getId());
            }
        }
        String className = profile.getClass().getName();
        return className.contains("GradleRunConfiguration") || className.contains("ExternalSystemRunConfiguration");
    }

    /**
     * Checks if the given RunProfile is a standard IDEA Java run configuration (running via IDEA JPS).
     */
    public static boolean isIdeaJavaRunConfiguration(@Nullable RunProfile profile) {
        if (profile == null) {
            return false;
        }
        return (profile instanceof ModuleRunProfile) && !isGradleRunConfiguration(profile);
    }

    /**
     * Generates or retrieves the Gradle init-script file for HotSwapAgent dynamic injection.
     */
    @NotNull
    public static File getOrGenerateInitScript(@NotNull Project project) {
        File folder = MyUtils.getHotSwapFolder();
        if (!folder.exists()) {
            folder.mkdirs();
        }
        File initScriptFile = new File(folder, INIT_SCRIPT_NAME);

        HotSwapHelperPluginSettingsProvider.State currentState =
                HotSwapHelperPluginSettingsProvider.Companion.getInstance(project).getCurrentState();

        String agentPath = MyUtils.getHotSwapJarPath().getAbsolutePath();
        if (currentState.getUseExternalHotSwapAgentFile()) {
            agentPath = currentState.getAgentPath();
        }
        agentPath = agentPath.replace('\\', '/');

        StringBuilder disabledPluginBlock = new StringBuilder();
        Set<String> disabledPlugins = currentState.getDisabledPlugins();
        if (disabledPlugins != null && !disabledPlugins.isEmpty()) {
            String join = Joiner.on(",").join(disabledPlugins);
            if (StringUtils.isNotBlank(join)) {
                disabledPluginBlock.append("                argsToAdd.add(\"-Dhotswapagent.disablePlugin=").append(join).append("\")\n");
            }
        }

        String scriptContent = "// Generated by HotSwapHelper IDEA Plugin for Gradle HotSwap\n" +
                "allprojects {\n" +
                "    tasks.withType(JavaExec) {\n" +
                "        def agentJar = new File('" + agentPath + "')\n" +
                "        if (agentJar.exists()) {\n" +
                "            def currentArgs = getJvmArgs() ?: []\n" +
                "            def alreadyAdded = currentArgs.any { it != null && it.contains(\"hotswap-agent\") }\n" +
                "            if (!alreadyAdded) {\n" +
                "                def javaVersionStr = System.getProperty(\"java.version\")\n" +
                "                int majorVersion = 17\n" +
                "                if (javaVersionStr != null) {\n" +
                "                    if (javaVersionStr.startsWith(\"1.8\")) {\n" +
                "                        majorVersion = 8\n" +
                "                    } else {\n" +
                "                        def dotIndex = javaVersionStr.indexOf('.')\n" +
                "                        if (dotIndex > 0) {\n" +
                "                            try {\n" +
                "                                majorVersion = Integer.parseInt(javaVersionStr.substring(0, dotIndex))\n" +
                "                            } catch (Exception ignored) {\n" +
                "                                majorVersion = 17\n" +
                "                            }\n" +
                "                        } else {\n" +
                "                            try {\n" +
                "                                majorVersion = Integer.parseInt(javaVersionStr)\n" +
                "                            } catch (Exception ignored) {\n" +
                "                                majorVersion = 17\n" +
                "                            }\n" +
                "                        }\n" +
                "                    }\n" +
                "                }\n" +
                "\n" +
                "                def argsToAdd = [\"-javaagent:\" + agentJar.absolutePath]\n" +
                "                if (majorVersion == 8) {\n" +
                "                    argsToAdd.add(\"-XX:+IgnoreUnrecognizedVMOptions\")\n" +
                "                    def javaHome = System.getProperty(\"java.home\")\n" +
                "                    def isMac = System.getProperty(\"os.name\", \"\").toLowerCase().contains(\"mac\") || System.getProperty(\"os.name\", \"\").toLowerCase().contains(\"darwin\")\n" +
                "                    def isArm = System.getProperty(\"os.arch\", \"\").toLowerCase().contains(\"aarch64\") || System.getProperty(\"os.arch\", \"\").toLowerCase().contains(\"arm64\")\n" +
                "                    def dcevmExists = false\n" +
                "                    if (javaHome != null && !(isMac && isArm)) {\n" +
                "                        dcevmExists = new File(javaHome, \"bin/dcevm\").exists() || new File(javaHome, \"lib/dcevm\").exists() || new File(javaHome, \"lib/amd64/dcevm\").exists()\n" +
                "                    }\n" +
                "                    if (dcevmExists) {\n" +
                "                        argsToAdd.add(\"-XXaltjvm=dcevm\")\n" +
                "                    }\n" +
                "                } else {\n" +
                "                    argsToAdd.add(\"-XX:+IgnoreUnrecognizedVMOptions\")\n" +
                "                    argsToAdd.add(\"-XX:+AllowEnhancedClassRedefinition\")\n" +
                "                    argsToAdd.add(\"-XX:HotswapAgent=external\")\n" +
                "                    if (majorVersion >= 17) {\n" +
                "                        argsToAdd.add(\"-XX:+ClassUnloading\")\n" +
                "                        argsToAdd.add(\"--add-opens=java.base/sun.nio.ch=ALL-UNNAMED\")\n" +
                "                        argsToAdd.add(\"--add-opens=java.base/java.lang=ALL-UNNAMED\")\n" +
                "                        argsToAdd.add(\"--add-opens=java.base/java.lang.reflect=ALL-UNNAMED\")\n" +
                "                        argsToAdd.add(\"--add-opens=java.base/java.io=ALL-UNNAMED\")\n" +
                "                        argsToAdd.add(\"--add-opens=java.base/sun.security.action=ALL-UNNAMED\")\n" +
                "                        argsToAdd.add(\"--add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED\")\n" +
                "                        argsToAdd.add(\"--add-opens=java.base/java.net=ALL-UNNAMED\")\n" +
                "                    }\n" +
                "                }\n" +
                disabledPluginBlock +
                "                jvmArgs(argsToAdd)\n" +
                "            }\n" +
                "        }\n" +
                "    }\n" +
                "}\n";

        try (FileWriter writer = new FileWriter(initScriptFile)) {
            writer.write(scriptContent);
        } catch (IOException e) {
            e.printStackTrace();
        }

        return initScriptFile;
    }

    /**
     * Appends the --init-script argument to Gradle task execution parameters if not already present.
     */
    public static void patchGradleScriptParameters(@NotNull ExternalSystemTaskExecutionSettings settings, @NotNull File initScript) {
        String scriptParams = settings.getScriptParameters();
        String initScriptArg = "--init-script \"" + initScript.getAbsolutePath().replace('\\', '/') + "\"";
        if (scriptParams == null || scriptParams.trim().isEmpty()) {
            settings.setScriptParameters(initScriptArg);
        } else if (!scriptParams.contains(INIT_SCRIPT_NAME)) {
            settings.setScriptParameters(scriptParams + " " + initScriptArg);
        }
    }

    /**
     * Removes the --init-script argument for HotSwap from Gradle task execution parameters if present.
     */
    public static void removeGradleScriptParameters(@NotNull ExternalSystemTaskExecutionSettings settings) {
        String scriptParams = settings.getScriptParameters();
        if (scriptParams != null && scriptParams.contains(INIT_SCRIPT_NAME)) {
            String cleaned = scriptParams.replaceAll("--init-script\\s+[\"'][^\"']*" + INIT_SCRIPT_NAME + "[\"']", "")
                    .replaceAll("--init-script\\s+[^\\s]*" + INIT_SCRIPT_NAME, "")
                    .replaceAll("\\s+", " ")
                    .trim();
            settings.setScriptParameters(cleaned);
        }
    }
}
